CREATE DATABASE COMP4911_DB;

GRANT ALL PRIVILEGES ON COMP4911_DB.* TO COMP4911_DB@localhost IDENTIFIED BY 'COMP4911_DB' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON COMP4911_DB.* TO COMP4911_DB@"%" IDENTIFIED BY 'COMP4911_DB' WITH GRANT OPTION;

DROP TABLE IF EXISTS COMP4911_DB.PROJECTEMPLOYEE;
DROP TABLE IF EXISTS COMP4911_DB.PACKAGEENGINEER;
DROP TABLE IF EXISTS COMP4911_DB.PACKAGEREPORT;
DROP TABLE IF EXISTS COMP4911_DB.MONTHLYREPORT;
DROP TABLE IF EXISTS COMP4911_DB.USERLEVEL;
DROP TABLE IF EXISTS COMP4911_DB.LABOURGRADE;
DROP TABLE IF EXISTS COMP4911_DB.HUMANRESOURCE;
DROP TABLE IF EXISTS COMP4911_DB.TIMESHEETAPPROVER;
DROP TABLE IF EXISTS COMP4911_DB.SUPERVISOR;
DROP TABLE IF EXISTS COMP4911_DB.PROJECTMANAGER;
DROP TABLE IF EXISTS COMP4911_DB.CREDENTIALS;
DROP TABLE IF EXISTS COMP4911_DB.TIMESHEETROW;
DROP TABLE IF EXISTS COMP4911_DB.TIMESHEET;
DROP TABLE IF EXISTS COMP4911_DB.EMPLOYEE;
DROP TABLE IF EXISTS COMP4911_DB.SUBPACKAGE;
DROP TABLE IF EXISTS COMP4911_DB.PACKAGE;
DROP TABLE IF EXISTS COMP4911_DB.PROJECT;

-- CREATE TABLE PROJECT
CREATE TABLE COMP4911_DB.PROJECT 
(
	PROJECT_ID	 	VARCHAR(10) 	NOT NULL UNIQUE,
	PROJECT_NAME	VARCHAR(60)		NOT NULL,
	START_DATE 		DATE 			NOT NULL,
	END_DATE 		DATE 			NOT NULL,
	MANAGER_FIRST 	VARCHAR(40) 	NOT NULL,
	MANAGER_LAST 	VARCHAR(40) 	NOT NULL,
	DESCRIPTION 	VARCHAR(255) 	NOT NULL,
	CLIENT_NAME 	VARCHAR(60) 	NOT NULL,
	PRIMARY KEY (PROJECT_ID)
);

-- CREATE TABLE EMPLOYEE
CREATE TABLE COMP4911_DB.EMPLOYEE
(
	EMPLOYEE_ID 			VARCHAR(10)		NOT NULL UNIQUE,
	FIRST_NAME 				VARCHAR(50) 	NOT NULL,
	LAST_NAME 				VARCHAR(50) 	NOT NULL,
	USER_TYPE 				TINYINT(1)  	NOT NULL,
	USER_POSITION 			VARCHAR(50) 	NOT NULL,
	HOME_NUMBER 			VARCHAR(50) 	NULL,
	CELL_NUMBER 			VARCHAR(50) 	NULL,
	ADDRESS 				VARCHAR(50)		NULL,
	PROVINCE 				VARCHAR(50) 	NULL,
	COUNTRY 				VARCHAR(50) 	NULL,
	POSTAL_CODE 			VARCHAR(50) 	NULL,
	EMAIL_ADDRESS 			VARCHAR(50) 	NULL,
	SICK_LEAVE_TIME_BALANCE DECIMAL(6,2)	NULL,
	VACATION_TIME_BALANCE 	DECIMAL(6,2)	NULL,
	SUPERVISOR_ID 			VARCHAR(10)		NOT NULL,
	PRIMARY KEY (EMPLOYEE_ID)
 );
 
 -- CREATE TABLE PACKAGE 
CREATE TABLE COMP4911_DB.PACKAGE
(
	PACKAGE_ID 			VARCHAR(10) 	NOT NULL UNIQUE,
	PROJECT_ID 			VARCHAR(10) 	NOT NULL,
	EMPLOYEE_ID			VARCHAR(10)		NOT NULL,
	ESTIMATED_COST 		DECIMAL(7,2) 	NOT NULL,
	CURRENT_COST 		DECIMAL(7,2) 	NOT NULL,
	PACKAGE_COMPLETION 	TINYINT(1) 		NOT NULL,
	SUB_PACKAGE_ID 		VARCHAR(10) 	NULL,
	PURPOSE 			VARCHAR(255) 	NOT NULL,
	INPUTS 				VARCHAR(255) 	NOT NULL,
	ACTIVITIES 			VARCHAR(255) 	NOT NULL,
	OUTPUTS 			VARCHAR(255) 	NOT NULL,
	PRIMARY KEY (PACKAGE_ID, PROJECT_ID, EMPLOYEE_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE CREDENTIALS
CREATE TABLE COMP4911_DB.CREDENTIALS
(
	EMPLOYEE_ID 	VARCHAR(10) 	NOT NULL UNIQUE,
	USER_NAME 		VARCHAR(50) 	NOT NULL UNIQUE,
	USER_PASSWORD   VARCHAR(50) 	NOT NULL,
	PRIMARY KEY (EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE PROJECTMANAGER
CREATE TABLE COMP4911_DB.PROJECTMANAGER
(
	PROJECTMANAGER_ID 	VARCHAR(10)		NOT NULL,
	EMPLOYEE_ID			VARCHAR(10)		NOT NULL,
	FIRST_NAME 			VARCHAR(50)		NOT NULL,
	LAST_NAME 			VARCHAR(50) 	NOT NULL,
	PRIMARY KEY (PROJECTMANAGER_ID, EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE SUPERVISOR
CREATE TABLE COMP4911_DB.SUPERVISOR
(
	SUPERVISOR_ID 	VARCHAR(10)		NOT NULL,
	EMPLOYEE_ID		VARCHAR(10)		NOT NULL,
	FIRST_NAME 		VARCHAR(50)		NOT NULL,
	LAST_NAME 		VARCHAR(50) 	NOT NULL,
	PRIMARY KEY (SUPERVISOR_ID, EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE TIMESHEETAPPROVER
CREATE TABLE COMP4911_DB.TIMESHEETAPPROVER
(
	TIMESHEETAPPROVER_ID VARCHAR(10) 	NOT NULL,
	EMPLOYEE_ID			 VARCHAR(10) 	NOT NULL,
	PROJECT_ID	 		 VARCHAR(10) 	NOT NULL,
	PRIMARY KEY (PROJECT_ID, TIMESHEETAPPROVER_ID, EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID)
);

-- CREATE TABLE HUMANRESOURCE
CREATE TABLE COMP4911_DB.HUMANRESOURCE
(
	HUMANRESOURCE_ID 	VARCHAR(10) 	NOT NULL,
	EMPLOYEE_ID			VARCHAR(10) 	NOT NULL,
	PRIMARY KEY (HUMANRESOURCE_ID, EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE LABOURGRADE
CREATE TABLE COMP4911_DB.LABOURGRADE
(
	PAY_LEVEL 		VARCHAR(2) 		NOT NULL,
	PAY_RATE 		DECIMAL(6,2)	NOT NULL,
	PAST_YEAR 		INT(4) 			NOT NULL,
	CURRENT_YEAR 	INT(4) 			NOT NULL,
	PRIMARY KEY (PAY_LEVEL)
);

-- CREATE TABLE USERLEVEL
CREATE TABLE COMP4911_DB.USERLEVEL
(
	EMPLOYEE_ID		VARCHAR(10) 	NOT NULL,
	DATE_CHANGED	DATE 			NOT NULL,
	PAY_LEVEL		VARCHAR(2) 		NOT NULL,
	CURRENT_YEAR	INT(4)			NOT NULL,
	PRIMARY KEY (EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID),
	FOREIGN KEY (PAY_LEVEL) REFERENCES COMP4911_DB.LABOURGRADE (PAY_LEVEL)
);

-- CREATE TABLE TIMESHEET
CREATE TABLE COMP4911_DB.TIMESHEET
(
	TIMESHEET_ID 		INTEGER(10) 	NOT NULL AUTO_INCREMENT,
	EMPLOYEE_ID 		VARCHAR(10) 	NOT NULL,
	FIRST_NAME 			VARCHAR(50) 	NOT NULL,
	LAST_NAME 			VARCHAR(50) 	NOT NULL,
	WEEK_NUMBER 		SMALLINT(4) 	NOT NULL,
	WEEK_ENDING 		DATE 			NOT NULL,
	TOTAL_HOURS_WEEKLY 	DECIMAL(4,1) 	NULL,
	OVERTIME 			DECIMAL(3,1) 	NULL,
	FLEXTIME 			DECIMAL(3,1) 	NULL,
	TIMESHEET_SIGNED 	VARCHAR(60) 	NOT NULL,
	APPROVED 			VARCHAR(30)	 	NOT NULL,
	PRIMARY KEY (TIMESHEET_ID,EMPLOYEE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE PROJECTEMPLOYEE
CREATE TABLE COMP4911_DB.PROJECTEMPLOYEE
(
	PROJECT_ID	VARCHAR(10) 	NOT NULL,
	EMPLOYEE_ID	VARCHAR(10) 	NOT NULL,
	PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE PACKAGEREPORT
CREATE TABLE COMP4911_DB.PACKAGEREPORT
(
	PROJECT_ID				VARCHAR(10)		NOT NULL,
	PACKAGE_ID 				VARCHAR(10) 	NOT NULL,
	REPORT_NUMBER			INT(3)			NOT NULL,
	REPORT_DATE				DATE			NOT NULL,
	EMPLOYEE_ID				VARCHAR(10)		NOT NULL,
	PROJECTMANAGER_ID 		VARCHAR(10)  	NOT NULL,
	WORK_COMPLETED			VARCHAR(255)	NOT NULL,
	WORK_PLANNED_NEXT		VARCHAR(255)	NOT NULL,
	ESTIMATED_TIME_COMPLETE	INT(3)			NOT NULL,
	PROBLEMS				VARCHAR(255)	NOT NULL,
	COMMENTS				VARCHAR(255)	NOT NULL,
	PRIMARY KEY (PROJECT_ID, PACKAGE_ID, REPORT_NUMBER),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (PACKAGE_ID) REFERENCES COMP4911_DB.PACKAGE (PACKAGE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE PACKAGEENGINEER
CREATE TABLE COMP4911_DB.PACKAGEENGINEER
(
	PROJECT_ID				VARCHAR(10)		NOT NULL,
	PACKAGE_ID 				VARCHAR(10) 	NOT NULL,
	EMPLOYEE_ID				VARCHAR(10)		NOT NULL,
	PRIMARY KEY (PROJECT_ID, PACKAGE_ID, EMPLOYEE_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (PACKAGE_ID) REFERENCES COMP4911_DB.PACKAGE (PACKAGE_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID)
);

-- CREATE TABLE TIMESHEETROW
CREATE TABLE COMP4911_DB.TIMESHEETROW
(
	TIMESHEET_ROW_ID 	INTEGER(10) 	NOT NULL AUTO_INCREMENT,
	TIMESHEET_ID 		INTEGER(10) 	NOT NULL,
	PROJECT_ID 			VARCHAR(10) 	NOT NULL,
	PACKAGE_ID 			VARCHAR(10) 	NOT NULL UNIQUE,
	TOTAL_HOURS 		DECIMAL(4,1) 	NULL,
	SATURDAY 			DECIMAL(3,1) 	NULL,
	SUNDAY 				DECIMAL(3,1) 	NULL,
	MONDAY 				DECIMAL(3,1) 	NULL,
	TUESDAY				DECIMAL(3,1) 	NULL,
	WEDNESDAY 			DECIMAL(3,1) 	NULL,
	THURSDAY 			DECIMAL(3,1) 	NULL,
	FRIDAY 				DECIMAL(3,1) 	NULL,
	NOTES 				VARCHAR(255) 	NULL,
	PRIMARY KEY (TIMESHEET_ROW_ID, TIMESHEET_ID),
	FOREIGN KEY (TIMESHEET_ID) REFERENCES COMP4911_DB.TIMESHEET (TIMESHEET_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (PACKAGE_ID) REFERENCES COMP4911_DB.PACKAGE (PACKAGE_ID)
);

-- CREATE TABLE SUB PACKAGE
CREATE TABLE COMP4911_DB.SUBPACKAGE
(
	SUB_PACKAGE_ID 		VARCHAR(10),
	PACKAGE_ID 			VARCHAR(10),
	DESCRIPTION 		VARCHAR(255),
	PACKAGE_COMPLETION 	TINYINT(1),
	PRIMARY KEY (SUB_PACKAGE_ID, PACKAGE_ID),
	FOREIGN KEY (PACKAGE_ID) REFERENCES COMP4911_DB.PACKAGE (PACKAGE_ID)
);

-- CREATE TABLE MONTHLYREPORT
CREATE TABLE COMP4911_DB.MONTHLYREPORT
(
	PROJECT_ID 			VARCHAR(10) 	NOT NULL,
	PROJECT_NAME			VARCHAR(60)		NOT NULL,
	EMPLOYEE_ID 			VARCHAR(10)		NOT NULL,
	PACKAGE_ID 				VARCHAR(10) 	NOT NULL,
	REPORT_DATE				DATE			NOT NULL,
	MAN_DAYS				INT(3)			NOT NULL,
	LABOUR_COST				DECIMAL(6,2)	NOT NULL,
	PROJECT_BUDGET			DECIMAL(6,2)	NOT NULL,
	ENGINEER_PLANNED		DECIMAL(6,2)	NOT NULL,
	ACTUAL_BUDGET_TODATE	DECIMAL(6,2)	NOT NULL,
	ESTIMATE_AT_COMPLETION	DECIMAL(6,2)	NOT NULL,
	_VARIANCE				DECIMAL(6,2)	NOT NULL,
	COMMENTS				VARCHAR(255)	NULL,
	STATUS					INT(3) 			NOT NULL,
	PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID, PACKAGE_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES COMP4911_DB.PROJECT (PROJECT_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES COMP4911_DB.EMPLOYEE (EMPLOYEE_ID),
	FOREIGN KEY (PACKAGE_ID) REFERENCES COMP4911_DB.PACKAGE (PACKAGE_ID)
);


INSERT INTO COMP4911_DB.EMPLOYEE VALUES ('E001', 'Admin', 'Root', 1, 'Administrator',
										 'Not Available', 'Not Available', 'Not Available', 
										 'Not Available', 'Not Available', 'Not Available',
										 'Not Available', 'Not Available', 'Not Available',
										 '1');

INSERT INTO COMP4911_DB.CREDENTIALS VALUES ('E001', 'admin', '123');